// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(TechShopDbContext))]
    [Migration("20220924091610_SeedLaptops")]
    partial class SeedLaptops
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_Tech_Shop.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Display = "13.3″ Full HD",
                            Model = "Dell Latitude 5320",
                            Price = 699m,
                            Processor = "11th Gen Intel® Core i5"
                        },
                        new
                        {
                            Id = 2,
                            Display = "11.6″ HD LED Display",
                            Model = "Samsung Chromebook 4 310XBA-KA1",
                            Price = 199m,
                            Processor = "Intel® Dual-Core"
                        },
                        new
                        {
                            Id = 3,
                            Display = "13.3″ Full HD IPS Touch Screen",
                            Model = "Lenovo IdeaPad Flex 5",
                            Price = 419m,
                            Processor = "Intel® Core i3"
                        },
                        new
                        {
                            Id = 4,
                            Display = "14” 4K Anti-glare",
                            Model = "Dell Latitude E7420",
                            Price = 899m,
                            Processor = "11th Gen Intel Core i7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
